### ISSUE TITLE
Meio estranho passar as envs assim

### ISSUE THREAD

**Issue by ChrisAmora** [EsdrasAmora/todo-app#1]
https://github.com/EsdrasAmora/todo-app/blob/e99b16a7f0facc850cbce6d348998b8046ea8666/package.json#L15

**Comment by EsdrasAmora** [comment]
sim, sabe um jeito melhor ? eu tentei colocar num commando separado e rodar tipo assim 
```
pnpm export-env && pnpm prisma migrate reset
```
